#:schema node_modules/wrangler/config-schema.json
name = "bi-shop"
pages_build_output_dir = "dist"
compatibility_date = "2026-07-08"

[[kv_namespaces]]
binding = "TOYS_KV"
id = "2a632e5ea0bb49568704d3d8d6698496"
